title: Connecting Things
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7607046
  brandStrength: 0.75
  rhythmicContrast: 0.5
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-75418715-1
  facebook: null
name: connectingthings
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49257
layout_spectrum: 1
