name: connectingthings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49257
title: Connecting Things
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.25
  lightness: 0.5008432
  saturation: 0.7607046
  rhythmicContrast: 0.2938699
purpose: []
