typography_spectrum: 0.4755481
color:
  saturation: 0.7607046
  brandStrength: 0.75
  rhythmicContrast: 0.5
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  twitter: null
  google: UA-75418715-1
  facebook: null
name: connectingthings
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Test
    id: d3ccb20e-2140-4443-ac1d-0e125586bafe
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Connecting Things
description: Bits and Pieces on Ideation
purpose: []
